### ISSUE TITLE
This line doesnt make sense, typo?

### ISSUE THREAD

**Issue by brookebachman** [learn-co-curriculum/ruby-oo-fundamentals-attribute-accessors#1]
When opening up a class, attr_accessor **and friends** allow you to get a high level overview of the class right from the start.

**Comment by maxwellbenton** [comment]
Hi @brookebachman00,

Thank you for providing this feedback. We've updated this sentence to prevent confusion for future students, which should resolve this issue.

Thank you for contributing!
